# Generated by Django 2.2.10 on 2020-02-11 15:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender',
                 models.CharField(choices=[('M', 'Male'), ('F', 'Female')],
                                  max_length=1)),
                ('pesel', models.CharField(max_length=11)),
                ('age', models.SmallIntegerField(default=18)),
                ('education', models.CharField(
                    choices=[('1', 'podstawowe'), ('2', 'gimnazjalne'),
                             ('3', 'policealne'), ('4', 'pomaturalne'),
                             ('5', 'wyższe I stopnia licencjat'),
                             ('6', 'wyższe I stopnia inżynier'),
                             ('7', 'wyższe II stopnia'), ('8', 'doktorat')],
                    max_length=1)),
                ('street', models.TextField()),
                ('street_no', models.CharField(max_length=10)),
                ('street_building_no', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('voivodeship', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('commune', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('start_project_date',
                 models.DateField(default=django.utils.timezone.now)),
                ('end_project_date',
                 models.DateField(default=django.utils.timezone.now)),
                ('start_support_date',
                 models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(
                    choices=[('e', 'Unemployment'), ('n', 'No working'),
                             ('w', 'Working')], max_length=1)),
                ('profession', models.CharField(max_length=1000)),
                ('work_name', models.CharField(max_length=1000)),
                ('origin', models.CharField(
                    choices=[('y', 'Yes'), ('n', 'No'), ('r', 'Refusal')],
                    max_length=1)),
                ('homeless', models.CharField(
                    choices=[('y', 'Yes'), ('n', 'No'), ('r', 'Refusal')],
                    max_length=1)),
                ('disabled_person', models.CharField(
                    choices=[('y', 'Yes'), ('n', 'No'), ('r', 'Refusal')],
                    max_length=1)),
                ('social_disadvantage', models.CharField(
                    choices=[('y', 'Yes'), ('n', 'No'), ('r', 'Refusal')],
                    max_length=1)),
                ('course_id', models.CharField(max_length=1000)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
