# Generated by Django 2.2.10 on 2020-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20200223_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='pesel',
            field=models.CharField(
                help_text='For people who do not have a PESEL number, type in NONE.',
                max_length=11, verbose_name='PESEL'),
        ),
    ]
