# Generated by Django 2.2.10 on 2020-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200514_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='email',
            field=models.CharField(help_text='Enter the address mail for contact.', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='phone',
            field=models.CharField(help_text='Provide the contact telephone number.', max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='voivodeship',
            field=models.CharField(blank=True, choices=[('greater_poland', 'Greater Poland'), ('kuyavia-pomerania', 'Kuyavian-Pomeranian'), ('lesser_poland', 'Lesser Poland'), ('lodz', 'Lodz'), ('lower_silesia', 'Lower Silesian'), ('lublin', 'Lublin'), ('lubusz', 'Lubusz'), ('masovia', 'Masovian'), ('opole', 'Opole'), ('podlasie', 'Podlasie'), ('pomerania', 'Pomeranian'), ('silesia', 'Silesian'), ('subcarpatia', 'Subcarpathian'), ('swietokrzyskie', 'Swietokrzyskie'), ('warmia-masuria', 'Warmian-Masurian'), ('west_pomerania', 'West Pomeranian')], max_length=30, null=True, verbose_name='Voivodeship'),
        ),
    ]
