# Generated by Django 2.2.10 on 2020-07-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200717_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='phone',
            field=models.CharField(help_text='Provide the contact telephone number.', max_length=30, verbose_name='Phone'),
        ),
    ]
