# Generated by Django 2.2.10 on 2020-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_auto_20200720_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationcourse',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country'),
        ),
    ]
