# Generated by Django 2.2.10 on 2021-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_auto_20210121_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='course_id',
            field=models.CharField(max_length=1000, verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='email',
            field=models.CharField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='language_code',
            field=models.CharField(max_length=1000, verbose_name='Form language'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='street_building_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Building no'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='street_no',
            field=models.CharField(max_length=10, verbose_name='Street no'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='work_name',
            field=models.CharField(max_length=1000, verbose_name='Job title'),
        ),
    ]
