# Generated by Django 2.2.10 on 2021-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_auto_20210204_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='profession',
            field=models.CharField(blank=True, choices=[('', ''), ('Vocational teacher', 'Vocational teacher'),
                                                        ('General education teacher', 'General education teacher'),
                                                        ('Kindergarten teacher', 'Kindergarten teacher'), (
                                                        'Employee in higher education institution',
                                                        'Employee in higher education institution'), (
                                                        'Labor market institution employee',
                                                        'Labor market institution employee'),
                                                        ('Health care worker', 'Health care worker'),
                                                        ('Farmer', 'Farmer'), (
                                                            'Key employee in social assistance and integration institution',
                                                            'Key employee in social assistance and integration institution'),
                                                        ('Employee in family and foster care support institution',
                                                         'Employee in family and foster care support institution'), (
                                                            'Employee in social economy support center',
                                                            'Employee in social economy support center'), (
                                                            'Employee in psychological and pedagogical counseling center',
                                                            'Employee in psychological and pedagogical counseling center'),
                                                        ('Practical vocational instructor',
                                                         'Practical vocational instructor'), ('other', 'other')],
                                   max_length=1000, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='work_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Job title'),
        ),
    ]
