# Generated by Django 2.2.10 on 2021-07-12 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_auto_20210621_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationcourse',
            old_name='nationality',
            new_name='citizenship',
        ),
    ]
