# Generated by Django 2.2.10 on 2021-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0019_auto_20210712_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcourse',
            name='age',
            field=models.SmallIntegerField(verbose_name='Age'),
        ),
    ]
